### ISSUE TITLE
[Question]After added existing solution, ServiceProxy Url is still valid?

### ISSUE THREAD

**Issue by heavenwing** [MedAnd/AspNetCore.DataProtection.ServiceFabric#4]
After dded existing solution, my App Name is not "ServiceFabric.DataProtection", could this service url still use this address "fabric:/ServiceFabric.DataProtection/DataProtectionService"?

**Comment by MedAnd** [comment]
That should be fine... you should be able to use (call) "fabric:/ServiceFabric.DataProtection/DataProtectionService" from any other Service Fabric application... are you getting an exception?

You should be able to just nuget include AspNetCore.DataProtection.ServiceFabric.Common in your application, which will then call "fabric:/ServiceFabric.DataProtection/DataProtectionService"

**Comment by heavenwing** [comment]
If publish your SF application into cluster directly, service uri "fabric:/ServiceFabric.DataProtection/DataProtectionService" is ok.
But when I install DataProtectionService into my own SF application with SFNuGet, service uri will be  "fabric:/MyApplication/AspNetCore.DataProtection.ServiceFabric".

**Comment by MedAnd** [comment]
Hi @heavenwing, the below branch is part two of the PR with Initial support for TargetFramework netcoreapp2.1. Wondering if it works for you?

https://github.com/MedAnd/AspNetCore.DataProtection.ServiceFabric/tree/PersistKeysToServiceFabricServiceUriUpgrade

**Comment by heavenwing** [comment]
It’s working in my repos, but I don’t try use your.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MedAnd** [comment]
Would you mind trying with your website project.. if it works I can publish new nugets and close this thread?

**Comment by MedAnd** [comment]
Closing this issue as I believe it's resolved.
